/** @file ctk_error_msg.h
    @brief CTK error messages.
    This file is automatically generated. */
const char *ctk_errlist[] = {
 "Generic error",  	/* CTK_ERROR_GENERIC */ 
 "Unknown error",  	/* CTK_ERROR_UNKNOWN */ 
 "File not found",  	/* CTK_ERROR_FILE_NOT_FOUND */ 
 "No such thread",  	/* CTK_ERROR_THREAD_NOT_FOUND */ 
 "Object not found",  	/* CTK_ERROR_NOT_FOUND */ 
 "Invalid ID",  	/* CTK_ERROR_BAD_ID */ 
 "Invalid file",  	/* CTK_ERROR_BAD_FILE */ 
 "Bad format",  	/* CTK_ERROR_BAD_FORMAT */ 
 "Bad address",  	/* CTK_ERROR_BAD_ADDRESS */ 
 "Invalid object",  	/* CTK_ERROR_BAD_OBJECT */ 
 "Invalid value",  	/* CTK_ERROR_BAD_VALUE */ 
 "Got a NULL object",  	/* CTK_ERROR_NULL_OBJECT */ 
 "Bad alignment",  	/* CTK_ERROR_BAD_ALIGNMENT */ 
 "Bad Elf image",  	/* CTK_ERROR_BAD_ELF */ 
 "Invalid Elf header",  	/* CTK_ERROR_BAD_ELF_HEADER */ 
 "Invalid Elf machine type",  	/* CTK_ERROR_BAD_ELF_MACHTYPE */ 
 "Invalid Elf object type",  	/* CTK_ERROR_BAD_ELF_TYPE */ 
 "No Elf segment to load",  	/* CTK_ERROR_NO_ELF_SEGMENT */ 
 "Not an executable file",  	/* CTK_ERROR_NOT_EXECUTABLE */ 
 "Not a regular file",  	/* CTK_ERROR_NOT_REGULAR_FILE */ 
 "File is too large",  	/* CTK_ERROR_FILE_TOO_LARGE */ 
 "No enough memory",  	/* CTK_ERROR_NO_MEMORY */ 
 "Not enough resource",  	/* CTK_ERROR_NO_RESOURCE */ 
 "Invalid flag",  	/* CTK_ERROR_BAD_FLAG */ 
 "Invalid argument",  	/* CTK_ERROR_BAD_ARGUMENT */ 
 "Invalid request",  	/* CTK_ERROR_BAD_REQUEST */ 
 "Out of range",  	/* CTK_ERROR_OUT_OF_RANGE */ 
 "Permission denied",  	/* CTK_ERROR_NO_PERMISSION */ 
 "Resource busy",  	/* CTK_ERROR_BUSY */ 
 "Not initialized",  	/* CTK_ERROR_NOT_INITIALIZED */ 
 "Not supported",  	/* CTK_ERROR_NOT_SUPPORTED */ 
 "Internal error",  	/* CTK_ERROR_INTERNAL */ 
 "Internal error (please retry)",  	/* CTK_ERROR_RETRY */ 
 "No data is available (on non-blocking call)",  	/* CTK_ERROR_NO_DATA */ 
 "The parameter is too big",  	/* CTK_ERROR_TOO_BIG */ 
 "The parameter is too small",  	/* CTK_ERROR_TOO_SMALL */ 
 "Too many objects or items",  	/* CTK_ERROR_TOO_MANY */ 
 "The SPE is not started",  	/* CTK_ERROR_SPE_NOT_STARTED */ 
 "The SPE is not running",  	/* CTK_ERROR_SPE_NOT_RUNNING */ 
 "The SPE is already running",  	/* CTK_ERROR_SPE_ALREADY_RUNNING */ 
 "Bad SPE status",  	/* CTK_ERROR_BAD_SPE_STATUS */ 
 "The item already exists",  	/* CTK_ERROR_ITEM_EXISTS */ 
 "The entry address is invalid",  	/* CTK_ERROR_INVALID_ENTRY_ADDR */ 
 "Bad task status",  	/* CTK_ERROR_BAD_TASK_STATUS */ 
 "The task is already queued or running",  	/* CTK_ERROR_TASK_ALREADY_QUEUED */ 
 "No such tasks.",  	/* CTK_ERROR_NO_TASK */ 
 "The task is detached.",  	/* CTK_ERROR_TASK_DETACHED */ 
 "Bad runtime type.",  	/* CTK_ERROR_BAD_RUNTIME_TYPE */ 
};
int ctk_nerr = 48;

